[tools]
python = "3.13"
uv = "latest"

[settings]
python.uv_venv_auto = true
experimental = true

[tasks.runserver]
run = "uv run manage.py runserver 0.0.0.0:8000"

[tasks.makemigrations]
run = "uv run manage.py makemigrations"